services:
  registrymaster:
    image: registry:v1
    build:
      context: ./CustomServiceRegistry.RegistryApi
      dockerfile: Dockerfile
    ports:
      - "5165:80"
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "300M"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    restart: unless-stopped
    container_name: registrymaster
    depends_on:
      - mongo
 
  registryslave:
    image: registry:v1
    build:
      context: ./CustomServiceRegistry.RegistryApi
      dockerfile: Dockerfile
    ports:
      - "5166:80"
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100M"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    restart: unless-stopped
    container_name: registryslave
    depends_on:
      - mongo
 
  registryslavebackup:
    image: registry:v1
    build:
      context: ./CustomServiceRegistry.RegistryApi
      dockerfile: Dockerfile
    ports:
      - "5167:80"
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100M"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    restart: unless-stopped
    container_name: registryslavebackup
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:81"
    networks:
      - app_network
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - ${MONGO_MOUNT_PATH}:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

networks:
  app_network:
    driver: bridge
